name: jupyter_dask

channels:
  - conda-forge

dependencies:
  - python=3.11
  # Jupyter and Dask specific
  - dask[complete]
  - dask-jobqueue
  - jupyterlab>=3,<4
  - dask-labextension
  - jupyterlab-git
  # other libraries
  - pip
  - pip:
    - dcachefs>=0.1.7
