name: jupyter_dask

channels:
  - conda-forge

dependencies:
  - python=3.10
  - dask[complete]
  - dask-jobqueue
  - jupyterlab>=3
  - dask-labextension
  - jupyterlab-git
  - gdal
  - xarray
  - rioxarray
  - matplotlib 
  - h5netcdf
  - zarr
  - pip
  - pip:
    - stac2dcache
    - /project/stursdat/Software/stm/. 
    - /project/stursdat/Software/sarxarray/.