name: jupyter_dask

channels:
  - conda-forge

dependencies:
  - python
  - dask[complete] 
  - dask-jobqueue
  - jupyterlab>=3
  - dask-labextension
  - jupyterlab-git
  - pip
  - pip:
    - dcachefs
