jobqueue:
  slurm:
    name: dask-worker

    # Dask worker options
    cores: 4                  # Total number of cores per job
    memory: '30GiB'           # Total amount of memory per job
    processes: 1              # Number of Python processes per job

#     interface: null             # Network interface to use like eth0 or ib0
#     death-timeout: 60           # Number of seconds to wait if a worker can not find a scheduler
    local-directory: '$TMPDIR'  # Location of fast local storage like /scratch or $TMPDIR
#     extra: []

    # SLURM resource manager options
#     shebang: "#!/usr/bin/env bash"
    queue: 'normal'
#     project: null
    walltime: '00:30:00'
#     env-extra: []
    job-cpu: 4
#     job-mem: null
#     job-extra: []
#     log-directory: null
    
    # Scheduler options
#     scheduler-options: {}

#   local:
#     name: dask-worker
#     # Dask worker options
#     cores: null                 # Total number of cores per job
#     memory: null                # Total amount of memory per job
#     processes: null                # Number of Python processes per job

#     interface: null             # Network interface to use like eth0 or ib0
#     death-timeout: 60           # Number of seconds to wait if a worker can not find a scheduler
#     local-directory: null       # Location of fast local storage like /scratch or $TMPDIR
#     extra: []

#     env-extra: []
#     job-extra: []
#     log-directory: null
    
#     # Scheduler options
#     scheduler-options: {}
